Tnmk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', include('home.urls')),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home_url'),
    path('<str:slug>/', views.articles, name='articles_url'),
    path('<str:slug>/edit_comment/<int:id>/', views.edit_comment, name='edit_comment_url'),
    path('<str:slug>/delete_comment/<int:id>/', views.delete_comment, name='delete_comment_url'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Chat(models.Model):
    '''
    Класс для создания личных\общих чатов
    '''
    group_name = models.CharField(max_length=50)
    creater = models.ForeignKey(User, on_delete=models.CASCADE)
    members = models.ManyToManyField(User, verbose_name="Участник", related_name='members', default=User)
    image_chat = models.ImageField(null=True, blank=True, upload_to="image_chat", verbose_name='Фото беседы', default='group_chat')

    def __str__(self):
        return self.group_name

    def get_absolute_url(self):
        return reverse('private_chat_url', kwargs={'id': self.id})


class ReadMessage(models.Model):
    '''
    Прочитано сообщение или нет
    '''
    room_id = models.TextField('Id комнаты', max_length=30)
    message_id = models.TextField('Id сообщения', max_length=30)
    recipient = models.TextField('id получателей', max_length=30)
    is_read = models.BooleanField('Прочитано', default=False)


class Message(models.Model):
    '''
    Класс для создания сообщения
    '''
    author = models.ForeignKey(User, verbose_name="Отправитель", on_delete=models.CASCADE)
    recipient = models.ForeignKey(Chat, related_name='received_messages', verbose_name="Получатель", on_delete=models.CASCADE)
    content = models.TextField("Сообщение", default='Нет сообщения', max_length=2000)
    image = models.TextField("Фотографии", blank=True, null=True)
    file = models.TextField("Файл", blank=True, null=True)
    timestamp = models.DateTimeField('Дата сообщения', auto_now_add=True)

    class Meta:
        verbose_name = u'Сообщение'
        verbose_name_plural = u'Сообщения'

    def __str__(self):
        return self.content

home/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.html import mark_safe
from django.contrib.auth.models import User


class Article(models.Model):
    """
    Модель для создания новостей на главной странице
    """
    title = models.CharField(max_length=70, verbose_name='Название статьи')
    slug = models.SlugField(verbose_name="URL адрес статьи", unique=True, blank=True, null=True)
    text_article = models.TextField(max_length=5000, verbose_name='Содержание статьи', blank=True, null=True)
    image = models.ImageField(upload_to='Articles', verbose_name='Главное изображение статьи', blank=True, null=True)
    image_two = models.ImageField(upload_to='Articles', verbose_name='Дополнительное изображение', blank=True, null=True)
    image_three = models.ImageField(upload_to='Articles', verbose_name='Дополнительное изображение', blank=True, null=True)

    #def image_tag(self):
        #return mark_safe(u'<a href="{0}" target="_blank"><img src="{0}" width="150" height="130"/></a>'.format(self.image.url))

    def get_absolute_url(self):
        return reverse('articles_url', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = u'Новость'
        verbose_name_plural = u'Новости'

    def __str__(self):
        return self.title


class Comment(models.Model):
    '''
    Комментарии к записям на главной странице
    '''
    post = models.ForeignKey(Article, related_name='post',
                             on_delete=models.CASCADE, editable=False)
    author = models.OneToOneField(User, on_delete=models.CASCADE,
                               verbose_name=u"Автор", related_name="author", editable=False)
    body = models.TextField(max_length=1000, verbose_name=u"Текст комментария")
    created = models.DateTimeField(auto_now_add=True, verbose_name=u"Дата создания")
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)
        verbose_name = u'Коммертарий'
        verbose_name_plural = u'Комментарии'

    def __str__(self):
        return self.body


class Question(models.Model):
    """
    Вопрос для опроса
    """
    article_id = models.OneToOneField(Article, on_delete=models.CASCADE, related_name='r_article')
    title = models.CharField(max_length=200, verbose_name="Вопрос")
    date_published = models.DateTimeField(verbose_name="Дата публикации", auto_now_add=True)
    is_active = models.BooleanField(verbose_name="Опубликован")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'


class Answer(models.Model):
    """
    Вариант ответа на вопрос
    """
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='r_question')
    answer = models.CharField(max_length=200, verbose_name="Ответ")
    votes = models.IntegerField(verbose_name="Голосов", default=0)

    def __str__(self):
        return self.answer

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'


class AnswerUser(models.Model):
    """
    Ответы пользователей
    """
    answer_id = models.OneToOneField(Answer, on_delete=models.CASCADE, related_name='r_question')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='r_user')

    # def __str__(self):
    #     return self.answer_id

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

home/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    '''
    Комментарии к новостям на главной странице
    '''
    body = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ('body',)


class QuestionForm(forms.ModelForm):
    """
    Форма для опросов
    """
    class Meta:
        model = AnswerUser
        fields = ('answer_id',)

# class AnswerForm(forms.ModelForm):
#     """
#     Форма для опросов
#     """
#     class Meta:
#         model = AnswerUser
#         fields = ('answer',)

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Article, Question, Answer
from django.db.models import Q
from .forms import *
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.utils.safestring import mark_safe
import json


#Загрузка главной страницы
def home(request):
    #Поиск пользователей
    search_news = request.GET.get('search_news','')
    if search_news:
        article = Article.objects.filter(Q(title__icontains=search_news) | Q(text_article__icontains=search_news))
    else:
        article = Article.objects.order_by('-pk')

    #Пагинация новостей
    paginator = Paginator(article, 9)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    is_paginated = page.has_other_pages()
    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''
    data = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url,
        'username': mark_safe(json.dumps(request.user.username)),
    }
    return render(request, 'home/home.html', data)


# Страница для каждой записи
def articles(request, slug):
    articles = get_object_or_404(Article, slug__iexact=slug)
    question = Question.objects.get(article_id=articles.id)
    answers = Answer.objects.filter(question_id=question.id)
    for answer in answers:
        try:
            AnswerUser.objects.get(answer_id=answer)
        except:
            if request.method == 'POST':
                answer_form = QuestionForm(request.POST)
                if request.POST.get('ans') == 'answer':
                    answer_id = Answer.objects.get(id=request.POST.get('answerUser'))
                    votes = answer_id.votes + 1
                    Answer.objects.filter(id=request.POST.get('answerUser')).update(votes=votes)
                    AnswerUser.objects.create(user=request.user, answer_id=answer_id)
                    print('Новая запись')
                    return redirect(articles)
        # Комментарии к записям
        else:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment_form.instance.author = request.user
                comment_form.instance.post = articles
                comment_form.save()
                return redirect(articles)
    # Проверка отвечал ли пользователь
    list_answers = []
    # для подсчета количества голосов
    votes = 0
    for answer in answers:
        try:
            count_votes = answer.votes
            votes += count_votes
            AnswerUser.objects.get(answer_id=answer.id)
            list_answers.append('1')
        except:
            pass
    try:
        list_answers[0]
        answer_form = '1'
    except IndexError:
        answer_form = QuestionForm(request.POST)
    comment_form = CommentForm()

    comments = Comment.objects.order_by('-pk').filter(post=articles)
    context = {
        'votes': votes,
        'question': question,
        'answer_form': answer_form,
        'articles': articles,
        'answer': question.r_question.all(),
        'comments':     comments,
        'comment_form': comment_form,
        'username': mark_safe(json.dumps(request.user.username)),
    }
    return render(request, 'home/one_news.html', context)


@login_required
def edit_comment(request, id, slug):
    try:
        articles = get_object_or_404(Article, slug__iexact=slug)
        comment_edit = Comment.objects.get(id=id)
        if request.method == "POST":
            comment_edit.body = request.POST.get("body")
            #post.image = request.POST.get('image')
            comment_edit.save()
            return redirect(articles)
        else:
            form = CommentForm()
            return render(request, "home/edit_comment.html",
                          {
                              "comment": comment_edit,
                           'username': mark_safe(json.dumps(request.user.username)),})
    except Comment.DoesNotExist:
        return HttpResponseNotFound("<h2>Post not found</h2>")


#Удаление комментариев
def delete_comment(request, id, slug):
    try:
        articles = get_object_or_404(Article, slug__iexact=slug)
        comment = Comment.objects.get(id=id)
        comment.delete()
        return redirect(articles)
    except Comment.DoesNotExist:
        return HttpResponseNotFound("<h2>Post not found</h2>")

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
      <meta charset="UTF-8">
      <title>{% block title %}{% endblock %}</title>
      {% block link %}{% endblock %}
      <link rel="shortcut icon" href="/media/favicon.ico" type="image/x-icon">
      <link rel="stylesheet" href="/static/style.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
      <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
<body>
  <ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'home_url' %}">Главная</a>
  </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'list_users_url' %}">Список пользователей</a>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="new_message1" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Моя страница</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'my_page_url' %}">Моя страница</a>
      <a class="dropdown-item" href="{% url 'chat_url' %}" id ="new_message2">Сообщения</a>
      <a class="dropdown-item" href="{% url 'my_page_edit_url' %}">Редактировать</a>
      <a class="dropdown-item" href="{% url 'out' %}" style="color:#0056b3;" >Выйти</a>
    </div>
  </li>
    {% else %}
      <a class="nav-link" ><p>Пользователь не обнаружен</p></a>
      <li class="nav_item">
        <a class="nav-link" href="{% url 'user_login_url' %}">Войти</a>
      </li>
    {% endif %}
        {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="/admin/">Админка</a>
      </li>
      {% endif %}
  </ul>
  {% block content %}{% endblock %}
<!--  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>-->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
{% block script %}
  <div id="chat-log" style="position:fixed;right: 2%;bottom: 1%;width: 15%;"></div>

    <script src="{% static 'js/reconnecting-websocket.js' %}"></script>
  <script>
let blink = false;
var name = document.getElementsByTagName("title")[0].text;
  function new_message () {
    var newTxt="Новое уведомление";
      var oldTxt = name;
      var theTitle = document.getElementsByTagName("title")[0];
      var link = document.querySelector("link[rel*='shortcut icon']") || document.createElement('link');
      link.type = 'image/png';
      if (blink) {
        theTitle.text = newTxt;
        link.href = '/favicon-1.png';
        blink = false;
      } else {
        theTitle.text = oldTxt;
        link.href = '/favicon.png';
        blink = true;
      }
}



    var username = {{ user.id }};

    var userSocket = new ReconnectingWebSocket(
        'ws://' + window.location.host +
        '/ws/user/' + username + '/');

    userSocket.onopen = function(e) {
      fetchMessages();
    }

    userSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        if (data['command'] === 'messages') {
          for (let i=0; i<data['messages'].length; i++) {
            createMessage(data['messages'][i]);

          }
        } else if (data['command'] === 'new_message'){
          createMessage(data['message']);

        }
    };

    userSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#id_content').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.getElementById('id_content');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'command': 'new_message',
            'message': message,
            'from': username,
            'room_name': username

        }));
        messageInputDom.value = '';
    };

    function fetchMessages() {
      userSocket.send(JSON.stringify({'command': 'fetch_messages' }));
    }

    function createMessage(data) {

      var author = data['author'],
          first_name = data['first_name'],
          image = data['image'],
          id = data['id'],
          read_message = data['read_message'],
          slug = data['slug'],
          room_id = data['room_id'],
          timestamp = data['timestamp'],

          test = data['test']
          first_name1 = data['first_name1'],
          image1 = data['image1'],
          id1 = data['id1'],
          read_message1 = data['read_message1'],
          slug1 = data['slug1'],
          room_id1 = data['room_id1'],
          timestamp1 = data['timestamp1'],
          owner_class = 'text-right';
      if (author === username) {
        owner_class = 'text-left';
      }

    if (data['test'] == 'test'){

       var read = '<div class="media'+((read_message) ? ' new-message' : '')+'" id="new_message"><img src="'+image1+'" style="width:100px; padding:5px;" class="mr-3" alt="Не удалось загрузить изображение"><div class="media-body"><h7 class="mt-0"><a href="/account/'+slug1+'" style="float:left;">'+first_name1+'</a><p style="font-size:10pt; color: #5f5f5f; text-align:left;">&#160; &#160;'+timestamp1+'</p><h7>'+data.content1+'</h7></div></div>';
       let new_alert; new_alert = setInterval(function () {
           new_message()
          }, 1000);

}   else {

           var read = '<div class="media'+((read_message) ? ' new-message' : '')+'" id="new_message"><img src="'+image+'" style="width:100px; padding:5px;" class="mr-3" alt="Не удалось загрузить изображение"><div class="media-body"><h7 class="mt-0"><a href="/account/'+slug+'" style="float:left;">'+first_name+'</a><p style="font-size:10pt; color: #5f5f5f; text-align:left;">&#160; &#160;'+timestamp+'</p><h7>'+data.content+'</h7></div></div>';
          let new_alert; new_alert = setInterval(function () {
                   new_message()
                  }, 1000);
    }
      if (read_message == 1){
        $('<div class="card" id="chat_'+id+'" onClick="document.location=`/chat/'+room_id+'/`">'+read+'</div>').prependTo('#chat-log')
        let elem = document.getElementById('new_message1');
        let elem_1 = document.getElementById('new_message2');
        elem.childNodes[0].data ='Моя страница ●'
        elem_1.childNodes[0].data ='Сообщения ●'
        setTimeout(function()
        {
        $("#chat_"+id).remove();
        }, 10000);
}

   }

  </script>
{% endblock script %}

</body>
</html>

home/templates/home/edit_comment.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Редактирование комментария{% endblock %}
{% block content %}
<div class="mx-auto" style="width: 45%;">
  {% if user == comment.author %}
    <h2>Редактировать комментарий</h2>
      <form method="POST">
        {% csrf_token %}
        <textarea  name="body" class="form-control" required id="id_body">{{ comment.body }}</textarea>
        <button type="submit">Сохранить</button>
  {% else %}
    <div class="card text-center">
      Для вас эта страница недоступна (:
    </div>
  {% endif %}
      </form>

  <div id="id_content"></div>
<div id="chat-message-submit"></div>

{% endblock %}

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Домашняя страница{% endblock %}
{% block link %} <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> {% endblock %}
{% block content %}
<div class="mx-auto" style="width: 35%;">
  <form action="{% url 'home_url' %}">
    <input class="form-control" type="search" placeholder="Поиск новостей" name="search_news">
     <div class="card text-center">
       <div class="card-body">
      <button type="submit" style="width:220px;" class="btn btn-outline-primary">Поиск</button>
       </div>
     </div>
  </form>
<div class="container" style="padding-left:0; padding-right:0;">
{% for name in page_object.object_list %}
  <div class="card text-center">
  <div class="card-body">
    <h5 class="card-title">{{ name.title }}</h5>
    {% if name.image %}
    <a data-fancybox="gallery" href='{{ name.image.url }}'><img src="{{ name.image.url }}" class="card-img-top" style="width:150px;"></a>
    <a data-fancybox="gallery" href='{{ name.image_two.url }}'><img src="{{ name.image_two.url }}" class="card-img-top" style="width:150px;"></a>
    <a data-fancybox="gallery" href='{{ name.image_three.url }}'><img src="{{ name.image_three.url }}" class="card-img-top" style="width:150px;"></a>
    {% endif %}
      <div class="overflow-auto" >
        <p style="overflow: hidden;
            width: 60%;
            height: 100px;
            margin-left:20%;" class="card-text" >
            {{ name.text_article }}
        </p>
      </div>
    <a href="{{ name.get_absolute_url }}" class="btn btn-primary">Перейти</a>
  </div>
  </div>
{% endfor %}
</div>
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <a class="page-link" href="{{ prev_url }}">Назад</a>
    {% for n in page_object.paginator.page_range %}
      {%  if page_object.number == n %}
        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
      {% elif n > page_object.number|add:-3 and n < page_object.number|add:3  %}
        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
      {% endif %}
    {% endfor %}
      <a class="page-link" href="{{ next_url }}">Вперед</a>
  </ul>
</nav>


<div id="id_content"></div>
<div id="chat-message-submit"></div>
{% endblock %}

home/templates/home/one_news.html
{% extends 'home/base.html' %}
{% block title %} {{ articles.title }} {% endblock %}
{% load static %}
{% block content %}
<div class="mx-auto" style="width: 45%;;">
  <h1 style="text-align:center;margin-bottom:3%;">{{ articles.title }}</h1>
  <div class="card text-center">
    <div class="card-body" >
      {% if articles.image %}
        <a data-fancybox="gallery" href='{{ articles.image.url }}'><img style="width:200px" src="{{ articles.image.url }}"></a>
        <a data-fancybox="gallery" href='{{ articles.image_two.url }}'><img style="width:200px" src="{{ articles.image_two.url }}"></a>
        <a data-fancybox="gallery" href='{{ articles.image_three.url }}'><img style="width:200px" src="{{ articles.image_three.url }}"></a>
      {% endif %}
      {% if  answer_form == '1' %}
      <b>{{ question }}</b></br>
          {% for i in answer %}
      <p>{{ i }}</p><progress max="{{ votes }}" value="{{ i.votes }}"></progress></br>
          {% endfor %}
        {% else %}
            <form method="POST">
              {% csrf_token %}
              <b>{{ question }}</b></br>
              <input type="hidden" value="answer" name="ans">
              {% for i in answer %}
                {{ i }} - <input type="checkbox" name="answerUser" value="{{ i.id }}"></br>
              {% endfor %}
              <button type="submit" style="margin-top:1%; margin-bottom:1%; width:100%;" class="btn btn-outline-primary">Добавить</button>
            </form>
        {% endif %}

    </div>
  <div class="card text-center" >
    <p>{{ articles.text_article }}</p>
  </div>
  <form method="post">
    {% csrf_token %}
    <textarea class="form-control" name="body" cols="40" rows="3" maxlength="1000" required id="id_body"></textarea>
    <button type="submit" style="margin-top:1%; margin-bottom:1%; width:215px;" class="btn btn-outline-primary">Добавить</button>
  </form>
  {% for comment in comments %}
    <div class="media">
      <img src="/media/{{ comment.author.profile.image }}" style="width:100px; padding:5px;" class="mr-3" alt="Не удалось загрузить изображение">
      <div class="media-body">
        <h7 class="mt-0">
          <a href="{{ comment.author.profile.get_absolute_url }}" style="float:left;">
          {{ comment.author.profile.first_name }} {{ comment.author.profile.last_name }}
          </a>
          <p style="font-size:10pt; color: #5f5f5f; text-align:left;">&#160; &#160;{{ comment.created }}
          {% if user == comment.author %}
            <a href="{{ articles.get_absolute_url }}edit_comment/{{comment.id}}">Изменить</a> |
            <a onclick="if(confirm('Удалить?')){ return true } else { return false }" href="{{ articles.get_absolute_url }}delete_comment/{{comment.id}}">
              Удалить
            </a>
          {% endif %}
          </p>
        </h7>
        <p style="text-align:left;">{{ comment.body }}</p>
      </div>
    </div>
  {% endfor %}
  </div>
</div>

<div id="id_content"></div>
<div id="chat-message-submit"></div>

{% endblock %}