Tnmk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', include('home.urls')),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_login, name='user_login_url'),
    path('', views.out, name='out'),
    path('list_users/', views.list_users, name='list_users_url'),
    path('my_page/', views.my_page, name='my_page_url'),
    path('my_page/edit/', views.update_profile, name='my_page_edit_url'),
    path('my_page/edit_post/<int:id>/', views.update_post, name='edit_post_url'),
    path('my_page/delete_post/<int:id>/', views.delete_post, name='delete_post_url'),
    path('<str:slug>/', views.any_user, name='user_url'),
    #path('test/', views.any_user, name='user_url'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import reverse
from django.utils.html import mark_safe
from slugify import slugify


class Profile(models.Model):
    """
    Модель для личного профиля для пользователей
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, editable=False)
    first_name = models.CharField(max_length=30, verbose_name='Имя', default='Новый')
    last_name = models.CharField(max_length=30, verbose_name='Фамилия', default='Пользователь')
    position = models.CharField(max_length=100, verbose_name='Должность', default='Должность сотрудника')
    email = models.EmailField(max_length=100, verbose_name='Почта', default='1@1.11')
    number_phone = models.CharField(max_length=12, verbose_name='Номер телефона', default='+7')
    slug = models.SlugField(verbose_name="URL адрес", unique=True, blank=True, null=True, default='{}')
    bio = models.TextField(max_length=500, blank=True, verbose_name='Информация о человеке')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    image = models.ImageField(null=True, blank=True, upload_to="image_profil", verbose_name='Фото профиля', default='default_photo')

    def image_tag(self):
        return mark_safe(u'<a href="{0}" target="_blank"><img src="{0}" width="150" height="130"/></a>'.format(self.image.url))

    def get_absolute_url(self):
        return reverse('user_url', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = u'Данные пользователя'
        verbose_name_plural = u'Данные пользователей'

    def __str__(self):
        return self.first_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        return super(Profile, self).save(*args, **kwargs)

#Обновление модели автоматически сохраняется
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Post(models.Model):
    '''
    Посты на личной странице пользователя
    '''
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=u"Автор", related_name="posts")
    datetime = models.DateTimeField(verbose_name=u"Дата", auto_now_add=True)
    text = models.CharField(max_length=1000, verbose_name=u"Текст", null=True, blank=True)
    image = models.FileField(verbose_name=u"Картинка", upload_to="image_post", null=True, blank=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ["-datetime"]
        verbose_name = u'Пользовательская новость'
        verbose_name_plural = u'Пользовательские новости'

    def image_tag(self):
        return mark_safe(u'<a href="{0}" target="_blank"><img src="{0}" width="150" height="130"/></a>'.format(self.image.url))

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Chat(models.Model):
    '''
    Класс для создания личных\общих чатов
    '''
    group_name = models.CharField(max_length=50)
    creater = models.ForeignKey(User, on_delete=models.CASCADE)
    members = models.ManyToManyField(User, verbose_name="Участник", related_name='members', default=User)
    image_chat = models.ImageField(null=True, blank=True, upload_to="image_chat", verbose_name='Фото беседы', default='group_chat')

    def __str__(self):
        return self.group_name

    def get_absolute_url(self):
        return reverse('private_chat_url', kwargs={'id': self.id})


class ReadMessage(models.Model):
    '''
    Прочитано сообщение или нет
    '''
    room_id = models.TextField('Id комнаты', max_length=30)
    message_id = models.TextField('Id сообщения', max_length=30)
    recipient = models.TextField('id получателей', max_length=30)
    is_read = models.BooleanField('Прочитано', default=False)


class Message(models.Model):
    '''
    Класс для создания сообщения
    '''
    author = models.ForeignKey(User, verbose_name="Отправитель", on_delete=models.CASCADE)
    recipient = models.ForeignKey(Chat, related_name='received_messages', verbose_name="Получатель", on_delete=models.CASCADE)
    content = models.TextField("Сообщение", default='Нет сообщения', max_length=2000)
    image = models.TextField("Фотографии", blank=True, null=True)
    file = models.TextField("Файл", blank=True, null=True)
    timestamp = models.DateTimeField('Дата сообщения', auto_now_add=True)

    class Meta:
        verbose_name = u'Сообщение'
        verbose_name_plural = u'Сообщения'

    def __str__(self):
        return self.content

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import *


class UserLoginForm(AuthenticationForm):
    '''
    Форма для входа
    '''
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'Uname'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'Uname'}))


class ProfileForm(forms.ModelForm):
    '''
    Форма для редактирования личного профиля
    '''
    image = forms.ImageField(required=False)

    class Meta:
        model = Profile
        exclude = ['user']
        fields = '__all__'


class PostForm(forms.ModelForm):
    '''
    Форма для записей на личной странице
    '''
    image = forms.ImageField(required=False)

    class Meta:
        model = Post
        exclude = ['author', 'post']
        fields = '__all__'

chat/forms.py
from django import forms
from .models import *
from sanitizer.forms import SanitizedCharField


class MessageForm(forms.ModelForm):
    '''
    Форма для чата
    '''
    message = SanitizedCharField(strip=False)

    class Meta:
        model = Message
        fields = '__all__'
        # exclude = ['author', 'recipient', 'timestamp', 'is_readed']
        #fields = ('message',)#, 'image_message', 'file_message')


class ChatForm(forms.ModelForm):
    '''
    Форма для создания нового чата
    '''
    group_name = forms.CharField(required=False)
    class Meta:
        model = Chat
        fields = ('group_name', 'members', 'image_chat')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound
from .forms import *
from .models import *
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from chat.models import Chat, Message, ReadMessage
from chat.forms import ChatForm
from django.db.models import Count
from django.utils.safestring import mark_safe
import json


#Авторизация пользователей
def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home_url')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/auth.html', {'form': form})


#Выход из ЛК пользователя
def out(request):
    logout(request)
    return redirect('home_url')


#Создание и обновление данных профиля
@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('my_page_url')
        else:
            pass
    else:
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/edit.html', {
        'profile_form': profile_form,
        'username': mark_safe(json.dumps(request.user.username)),
    })


#Загрузка личной страницы
def my_page(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            return redirect("my_page_url")
        else:
            pass
    else:
        form = PostForm()

    context = {
            'posts': Post.objects.all(),
            'my_posts': Post.objects.filter(author=request.user),
            'form': form,
            'username': mark_safe(json.dumps(request.user.username)),
        }
    return render(request, 'accounts/my_page.html', context)


#Обновить данные поста
@login_required
def update_post(request, id):
    try:
        post = Post.objects.get(pk=id)
        if request.method == "POST":
            post_form = PostForm(request.POST, request.FILES, instance=post)
            post.text = request.POST.get("text")
            post.image = request.POST.get('image')
            post_form.save()
            post.save()
            return redirect("my_page_url")
        else:
            post_form = PostForm(instance=post)
            return render(request, "accounts/edit_post.html",
                          {
                              "post": post,
                              'post_form': post_form,
                              'username': mark_safe(json.dumps(request.user.username)),
                           })
    except Post.DoesNotExist:
        return HttpResponseNotFound("<h2>Post not found</h2>")


def delete_post(request, id):
    try:
        person = Post.objects.get(id=id)
        person.delete()
        return redirect("my_page_url")
    except Post.DoesNotExist:
        return HttpResponseNotFound("<h2>Post not found</h2>")


#Список всех пользователей
def list_users(request):
    #Поиск пользователей
    search_users = request.GET.get('search_name', '')
    if search_users:
        list_users = Profile.objects.filter(Q(first_name__icontains=search_users) | Q(last_name__icontains=search_users))
    else:
        list_users = Profile.objects.order_by('-pk')

    paginator = Paginator(list_users, 15)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    is_paginated = page.has_other_pages()
    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    data = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url,
        'username': mark_safe(json.dumps(request.user.username)),
    }
    return render(request, 'accounts/list_users.html',data)


# Личные страницы пользователей
def any_user(request, slug):
    # Получение данных профиля конкретного пользователя
    any_user = get_object_or_404(Profile, slug=slug)
    # Новости на личной странице пользователя
    user_context = Post.objects.filter(author=any_user.user)
    if request.method == 'POST':
        new_chat_form = ChatForm(request.POST)
        chat_prov = Chat.objects.filter((Q(creater=request.user) & Q(members=any_user.user.id)) |
                                        (Q(creater=any_user.user.id) & Q(members=request.user)))
        # Ищем личный чат между 2 пользователями
        if chat_prov:
            for i in chat_prov:
                # Если хоть один личный чат существует - не создаем комнату
                if i.members.count() == 2:
                    room_id = i.id
                    count = 2
                    if count == 2:
                        return redirect('/chat/' + str(room_id))
            # else:
            if new_chat_form.is_valid():
                new_chat_form.instance.creater = request.user
                # new_chat_form.instance.group_name = request.user.username + any_user.user.username
                new_chat_form.save()
                chat_id = new_chat_form.save().id
                # создание первого сообщения при создании чата
                message = Message.objects.create(
                    author=request.user,
                    recipient=new_chat_form.save(),
                    content=request.user.profile.first_name + ' открыл с вами чат!'
                )
                # создаем запись о чате(для непрочитанных сообщениях) в бд
                users = new_chat_form.save().members.all()
                for user in users:
                    new_data = ReadMessage.objects.create(room_id=chat_id, recipient=user.id, message_id=message.id)
                    new_data.save()

                return redirect(f'/chat/{chat_id}')
            else:
                HttpResponseNotFound("<h2>Введены неверные данные</h2>")
        else:
            if new_chat_form.is_valid():
                new_chat_form.instance.creater = request.user
                new_chat_form.save()
                chat_id = new_chat_form.save().id
                # создание первого сообщения при создании чата
                message = Message.objects.create(
                    author=request.user,
                    recipient=new_chat_form.save(),
                    content=request.user.profile.first_name + ' открыл с вами чат!'
                )
                # создаем запись о чате(для непрочитанных сообщениях) в бд
                users = new_chat_form.save().members.all()
                for user in users:
                    new_data = ReadMessage.objects.create(room_id=chat_id, recipient=user.id, message_id=message.id)
                    new_data.save()

                return redirect(f'/chat/{chat_id}')
            else:
                HttpResponseNotFound("<h2>Введены неверные данные</h2>")
    else:
        new_chat_form = ChatForm()
    context = {
             'user_data': any_user,
             'user_context': user_context,
             'start_chat': new_chat_form,
             'username': mark_safe(json.dumps(request.user.username)),
                }
    return render(request, 'accounts/profile_user.html', context)

accounts/templates/accounts/auth.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Авторизация{% endblock %}
{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'css/registr.css' %}"/>
{% endblock %}
{% block content %}
<div class="mx-auto" style="width: 220px;">
  <h2>Вход в аккаунт</h2>
      <form method="post">
        {% csrf_token %}
        Логин</br>
        {{ form.username }}
        Пароль</br>
        {{ form.password }}
        <button type="submit" style="margin-top:1%; width:215px;" class="btn btn-outline-primary">Войти</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/edit.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Редактирование {{ user.username }}{% endblock %}
{% block link %}
  <style type="text/css">
    textarea{width:300px;}
    input{width:300px;}
  </style>
{% endblock %}
{% block content %}
<div class="mx-auto" style="width: 220px;">
<form method="post"  enctype="multipart/form-data">
  {% csrf_token %}
  <label>Имя</label></br>
  {{ profile_form.first_name }}</br>
  <label>Фамилия</label></br>
  {{ profile_form.last_name }}</br>
  <label>Занимаемая должность</label></br>
  {{ profile_form.position }}</br>
  <label>Электронная почта</label></br>
  {{ profile_form.email }}</br>
  <label>Номер телефона</label></br>
  {{ profile_form.number_phone }}</br>
  <label>Информация о вас</label></br>
  {{ profile_form.bio }}</br>
  <label>Дата рождения</label></br>
  {{ profile_form.birth_date }}</br>
  {{ profile_form.image }}</br>
  <button type="submit" style="margin-top:2%; width:300px;" class="btn btn-outline-primary">Сохранить изменения</button>
</form>
</div>

<div id="id_content"></div>
<div id="chat-message-submit"></div>

{% endblock %}

accounts/templates/accounts/edit_post.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Редактирование {{ user.username }}{% endblock %}
{% block content %}
<div class="mx-auto" style="width: 45%;">
    <form method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
        <label>Изменения</label><br>
        <textarea class="form-control" name="text" cols="40" rows="3" maxlength="1000" required id="id_text" >{{post.text}}</textarea>
        {{ post_form.image }}
        <button type="submit" style="margin-top:1%; margin-bottom:1%; width:100%;" class="btn btn-outline-primary">Изменить</button>
    </form>
</div>

<div id="id_content"></div>
<div id="chat-message-submit"></div>

{% endblock %}

accounts/templates/accounts/list_users.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Список пользователей{% endblock %}
{% block content %}
<div class="mx-auto"style="width: 35%;;">
  <form action="{% url 'list_users_url' %}">
    <input class="form-control" type="search" placeholder="Поиск пользователей" name="search_name">
    <div class="card text-center">
       <div class="card-body">
        <button type="submit" style="width:220px;" class="btn btn-outline-primary">Поиск</button>
      </div>
    </div>
  </form>
{% for name in page_object.object_list %}
<div class="card text-center">
  <div class="card-body" style="height:200px;">
      <h4 class="card-title" > <a href="{{ name.get_absolute_url }}">{{ name.first_name }} {{ name.last_name }}</a></h4>
      <a data-fancybox="gallery" href="{{ name.image.url }}"><img src="{{ name.image.url }}" class="card-img-top" style="width:130px;"></a>
  </div>
</div>
{% endfor %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
      <a class="page-link" href="{{ prev_url }}">Назад</a>
      {% for n in page_object.paginator.page_range %}
        {%  if page_object.number == n %}
          <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
        {% elif n > page_object.number|add:-3 and n < page_object.number|add:3  %}
          <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
        {% endif %}
      {% endfor %}
      <a class="page-link" href="{{ next_url }}">Вперед</a>
  </ul>
</nav>
</div>

<div id="id_content"></div>
<div id="chat-message-submit"></div>

{% endblock %}

accounts/templates/accounts/my_page.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}{{ user.profile.first_name }} {{ user.profile.last_name }}{% endblock %}
{% block content %}
<div class="mx-auto" style="width: 35%;">
<div class="container">
  <div class="row" style="margin-top:3%;">
    <div class="col">
      <a data-fancybox="gallery" href='/media/{{ user.profile.image }}'><img src='/media/{{ user.profile.image }}' alt="Не удалось загрузить изображение" class="img-thumbnail" style="width:200px;"></a>
    </div>
    <div class="col">
      <h4>{{ user.profile.first_name }} {{ user.profile.last_name }}</h4>
      <p>Занимаемая должность: </br>{{ user.profile.position }}</p>
      <p>Электронная почта: </br><a href="mailto:{{ user.profile.email }}">{{ user.profile.email }}</a></p>
      <p>Номер телефона: </br>{{ user.profile.number_phone }}</p>
      <p>Информация о вас: </br>{{ user.profile.bio }}</p>
      <p>Дата рождения: </br>{{ user.profile.birth_date }}</p>
    </div>
      <div class="col">
        <button type="button" class="btn btn-outline-primary" onclick="document.location='edit/'">Редактировать</button>
          <p>Логин: {{ user.username}}</p>
      </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-12">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <textarea class="form-control" name="text" cols="40" rows="2" maxlength="1000" id="id_text"></textarea>
      {{ form.image }}
      <button type="submit" style="margin-top:1%; margin-bottom:1%; width:215px;" class="btn btn-outline-primary">Добавить</button>
    </form>
    </div>
    <div class="col">
    </div>
  </div>
{% for post in my_posts %}
<div class="card text-center" style="text-align:left !important">
  <div class="card-body">
    <div class="col-md-12">
      <h5 class="card-title">
        <p style="float:left;">
          {{ post.author.profile.first_name }} {{ post.author.profile.last_name }}
        </p>
        <p style="font-size:10pt; color: #5f5f5f;float:left;">&#160; &#160; {{ post.datetime }}&#160; &#160;
          <a href="edit_post/{{post.id}}">Изменить</a> |
          <a onclick="if(confirm('Удалить?')){ return true } else { return false }" href="delete_post/{{post.id}}">Удалить</a>
        </p>
      </h5>
    </div>
  <div class="col-md-12" style="float: left;">
    <p>{{ post.text }}</p>
  </div>
  {% if post.image.name %}
    <a data-fancybox="gallery" href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="card-img-top" style="max-width:100%;"></a>
  {% endif %}
  </div>
</div>
{% endfor %}

  <div id="id_content"></div>
<div id="chat-message-submit"></div>

{% endblock %}

accounts/templates/accounts/profile_user.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}{{ user_data.first_name }} {{ user_data.last_name }}{% endblock %}
{% block content %}
<div class="mx-auto" style="width: 35%;">
  <div class="container">
    <div class="row">
      <div class="col">
        <a data-fancybox="gallery" href='/media/{{ user_data.image }}'><img src='/media/{{ user_data.image }}' alt="Не удалось загрузить изображение" class="img-thumbnail" style="width:200px;"></a>
        <div>
          <form method="post">
            {% csrf_token %}
            <input type="hidden" name="group_name" maxlength="50" required="" id="id_group_name" value="От {{ user_data.user.username }} к {{ user }}">
            <select  name="members" required="" id="id_members" multiple="" style="display:none">
                <option selected value="{{ user_data.user.id }}">{{ user_data.user.username }}</option>
                <option selected value="{{ user.id }}">{{ user }}</option>
            </select>
          <button type="submit" style="margin-top:1%; margin-bottom:1%; width:100%;" class="btn btn-outline-primary">Написать</button>
        </form>
        </div>
      </div>
      <div class="col">
        <h4>{{ user_data.first_name }} {{ user_data.last_name }}</h4>
        <p>Должность: </br>{{ user_data.position }}</p>
        <p>Электронная почта: </br><a href="mailto:{{ user_data.email }}">{{ user_data.email }}</a></p>
        <p>Номер телефона: </br>{{ user_data.number_phone }}</p>
        <p>Информация о пользователе: </br>{{ user_data.bio }}</p>
        <p>Дата рождения: </br>{{ user_data.birth_date }}</p>
    </div>
  </div>
</div>
{% for post in user_context %}
<div class="card text-center" style="text-align:left !important">
  <div class="card-body">
    <div class="col-md-12">
      <h10 class="card-title" >
        <p style="float:left;">{{ post.author.profile.first_name }}
        {{ post.author.profile.last_name }}</p>
        <p style="font-size:10pt; color: #5f5f5f;">&#160; &#160;{{ post.datetime }}</p>
      </h10>
    </div>
    <div class="col-md-12" style="float: left;">
      <p>{{ post.text }}</p>
    </div>
    {% if post.image.name %}
    <a data-fancybox="gallery" href='/media/{{ user_data.image }}'><img src='/media/{{ user_data.image }}' class="card-img-top" style="max-width:100%;"></a>
    {% endif %}
  </div>
</div>
{% endfor %}
</div>

<div id="id_content"></div>
<div id="chat-message-submit"></div>

{% endblock %}

accounts/templates/accounts/registr.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Регистрация{% endblock %}
{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'css/registr.css' %}"/>
{% endblock %}
{% block content %}
  <h2>Регистрация</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button type="submit">Отправить</button>
  </form>
{% endblock %}